### Common

server:
  port: 33002
  tomcat:
    max-threads: 4

spring:
  application:
    name: UAA
  profiles:
    active: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yml"
    enabled: true

logging:
  level:
    root: INFO

com:
  chumbok:
    uaa:
      jwt:
        token-expiration-time-in-second: 300
        refresh-token-expiration-time-in-second: 1800
        token-issuer: Chumbok
        token-signing-key: TokenSigningKeyDoNotUseInProduction!

---

### Dev profile

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:uaa;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true

eureka:
  client:
    enabled: false

logging:
  level:
    com.chumbok: DEBUG

---

### Prod profile

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uaa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:33000/eureka/

logging:
  level:
    com.chumbok: DEBUG

---


### MySQL profile

spring:
  profiles: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uaa?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}


---

### Integration test profile

spring:
  profiles: it
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:uaa;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true


---

### Debug profile

spring:
  profiles: debug

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE